import os

table = [
	[],
	[0],
	[2,4],
	[10,12,18],
	[28,30,36,46]
]

elements = ["Hydrogen",
"Helium", 	
"Lithium", 
"Beryllium", 
"Boron", 
"Carbon", 
"Nitrogen", 
"Oxygen",
"Fluorine", 	
"Neon",
"Sodium", 
"Magnesium", 
"Aluminium", 
"Silicon", 
"Phosphorus", 
"Sulfur",
"Chlorine",
"Argon", 
"Potassium", 
"Calcium", 
"Scandium", 
"Titanium", 
"Vanadium", 
"Chromium", 
"Manganese", 
"Iron", 
"Cobalt", 
"Nickel",
"Copper",
"Zinc",
"Gallium", 
"Germanium", 
"Arsenic", 	
"Selenium",	
"Bromine", 	
"Krypton", 	
"Rubidium", 	
"Strontium", 
"Yttrium", 	
"Zirconium", 
"Niobium", 	
"Molybdenum", 
"Technetium", 
"Ruthenium", 
"Rhodium", 	
"Palladium", 
"Silver", 
"Cadmium", 	
"Indium", 
"Tin", 	
"Antimony", 	
"Tellurium", 
"Iodine", 
"Xenon", 
"Caesium", 	
"Barium", 
"Lanthanum", 
"Cerium", 
"Praseodymium", 	
"Neodymium", 	
"Promethium", 
"Samarium", 	
"Europium", 	
"Gadolinium", 
"Terbium", 	
"Dysprosium", 
"Holmium", 	
"Erbium", 
"Thulium", 
"Ytterbium", 
"Lutetium", 	
"Hafnium", 	
"Tantalum", 	
"Tungsten", 
"Rhenium", 	
"Osmium",
"Iridium", 
"Platinum", 	
"Gold", 
"Mercury", 	
"Thallium", 	
"Lead", 	
"Bismuth", 	
"Polonium", 	
"Astatine", 
"Radon", 	
"Francium", 	
"Radium", 
"Actinium", 	
"Thorium", 
"Protactinium", 	
"Uranium", 	
"Neptunium", 
"Plutonium", 
"Americium", 
"Curium", 
"Berkelium", 	
"Californium", 	
"Einsteinium", 
"Fermium", 	
"Mendelevium", 	
"Nobelium", 	
"Lawrencium", 
"Rutherfordium", 	
"Dubnium", 	
"Seaborgium", 	
"Bohrium", 	
"Hassium", 	
"Meitnerium", 
"Darmstadtium", 
"Roentgenium", 	
"Copernicium", 	
"Ununtrium", 
"Flerovium", 	
"Ununpentium", 	
"Livermorium", 	
"Ununseptium", 	
"Ununoctium" ]
	


os.system("cls")
print("======================================================")
q_number = input("Enter the quantum number separated by commas:")
result = q_number.split(",")

n = int(result[0])
l = int(result[1])
ml = float(result[2])
ms = float(result[3])

if ms == -0.5:
	e = ml + (3*l) + 2
elif ms == 0.5:
	e = ml + l + 1
else:
	print("Invalid quantum number. Please try again.")
print("number of valent electrons: " + str(int(e)))
print("total electrons: " + str(int(e + table[n][l])))
print("element: " + elements[int(e + table[n][l] - 1 )])
